name: docker-build-push

on: [push]

env: 
  DOCKER_REPO: project5

jobs:
  docker-build-push:
    runs-on: httpd-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - run: echo "post-checkout" && ls-lah && pwd

      - name: Log in
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:
        flavor: |
          latest=auto
        tags: |
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}


      - name: Docker buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
